services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: orchid
      POSTGRES_PASSWORD: orchid
      POSTGRES_DB: orchid
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
