import {
  pgTable,
  text,
  timestamp,
  integer,
  index,
  uniqueIndex,
  jsonb,
  customType,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

// Postgres `tsvector` — Drizzle has no first-class type for it, so we declare a
// minimal custom type. The column is a STORED generated column (see migration
// 0001_transcript_fts) derived from `transcript`; it is never written to
// directly, only read for matching (`@@`) and ranking (`ts_rank`).
const tsvector = customType<{ data: string }>({
  dataType: () => 'tsvector',
});

// Better Auth tables (generated by @better-auth/cli)
export {
  user,
  session,
  account,
  verification,
  organization,
  member,
  invitation,
  userRelations,
  sessionRelations,
  accountRelations,
  organizationRelations,
  memberRelations,
  invitationRelations,
} from './auth-schema';

import { user, organization } from './auth-schema';

// ── Our tables ──

export const orchidSession = pgTable(
  'orchid_session',
  {
    id: text('id').primaryKey(),
    userName: text('user_name'),
    userEmail: text('user_email'),
    workingDir: text('working_dir'),
    gitRemotes: jsonb('git_remotes'),
    branch: text('branch'),
    tool: text('tool'),
    transcript: text('transcript'),
    // STORED generated full-text-search vector over the transcript. Powers the
    // ranked search (`websearch_to_tsquery` @@ + `ts_rank`) that replaced the
    // old `ilike` full scan. Read-only at the app layer.
    transcriptSearch: tsvector('transcript_search').generatedAlwaysAs(
      sql`to_tsvector('english', left(coalesce("transcript", ''), 250000))`,
    ),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    status: text('status').notNull().default('active'),
    messageCount: integer('message_count').default(0),
    // Persisted token totals parsed from transcript `usage`. inputTokens folds
    // in cache_creation/cache_read (all input-side), so
    // inputTokens + outputTokens == the TUI's totalTokens. Powers the
    // PRs-÷-tokens metric without re-parsing every transcript on read.
    inputTokens: integer('input_tokens').default(0),
    outputTokens: integer('output_tokens').default(0),
    // Persisted Claude summary, generated server-side when a session flips to
    // `done`, so the session viewer renders the summary instantly (no click).
    // Null until generated; the on-demand /summary endpoint backfills + caches.
    summary: text('summary'),
    // Read-scoping visibility (P1-1). New captures default to 'private' (only the
    // owning user sees them); 'team' makes a session visible to the whole team.
    // Existing rows are backfilled to 'team' in migration 0008 so no current
    // session changes hands. The one source of truth for who-sees-what is
    // `visibleSessionScope` (queries.ts) / `scopeConditions` (api-app.ts).
    visibility: text('visibility').notNull().default('private'),
    userId: text('user_id').references(() => user.id),
    teamId: text('team_id').references(() => organization.id),
  },
  (t) => [
    index('idx_orchid_session_team').on(t.teamId),
    index('idx_orchid_session_user').on(t.userId),
    index('idx_orchid_session_transcript_fts').using('gin', t.transcriptSearch),
  ],
);

export const sessionCommit = pgTable(
  'session_commits',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    sessionId: text('session_id')
      .notNull()
      .references(() => orchidSession.id, { onDelete: 'cascade' }),
    commitSha: text('commit_sha').notNull(),
    branch: text('branch'),
    remote: text('remote'),
    message: text('message'),
    committedAt: timestamp('committed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('idx_session_commits_sha').on(t.commitSha),
    index('idx_session_commits_session').on(t.sessionId),
    // Idempotent commit↔session linking: dedup on (session_id, commit_sha) so a
    // re-post / re-backfill of the same commit is a no-op. Both the transcript
    // extractor and the deterministic ingest endpoint rely on this for their
    // `ON CONFLICT (session_id, commit_sha) DO NOTHING` upserts.
    uniqueIndex('uq_session_commits_session_sha').on(t.sessionId, t.commitSha),
  ],
);

// Session share grants (P1-3). An owner grants another user scoped READ access
// to one of their (private) sessions. Extends the P1-2 read-scope with a third
// disjunct: "OR the session is shared with me and the grant is not expired".
// One grant per (session, grantee) — upsertable via the unique index — so a
// re-share updates capability/expiry instead of stacking rows. `capability`
// is 'read' | 'continue'; both grant READ for now ('continue'/takeover is
// RFC #17, enforced later). The single source of truth for who-sees-what is
// `visibleSessionScope` (queries.ts) / `scopeConditions` (api-app.ts), both of
// which now read this table.
export const sessionShare = pgTable(
  'session_share',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    sessionId: text('session_id')
      .notNull()
      .references(() => orchidSession.id, { onDelete: 'cascade' }),
    granteeUserId: text('grantee_user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    capability: text('capability').notNull().default('read'),
    createdBy: text('created_by')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // One grant per (session, grantee): the upsert target. Re-sharing updates
    // the existing row's capability/expiry rather than inserting a duplicate.
    uniqueIndex('uq_session_share_session_grantee').on(t.sessionId, t.granteeUserId),
    // Grantee reverse-lookup: the read-scope's "shared with me" branch filters
    // by grantee_user_id, so it's the hot index.
    index('idx_session_share_grantee').on(t.granteeUserId),
  ],
);

export const apiKey = pgTable(
  'api_key',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    teamId: text('team_id').references(() => organization.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    keyHash: text('key_hash').notNull().unique(),
    keyPrefix: text('key_prefix').notNull(),
    lastUsed: timestamp('last_used', { withTimezone: true }),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('idx_api_key_user').on(t.userId), index('idx_api_key_hash').on(t.keyHash)],
);
